language: c++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - ccache
    - ninja-build
    - g++-5
    - gcc-5
    - g++-6
    - gcc-6
    - curl

env:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true
  
matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # LINUX
    # GCC 5
    - os: linux
      env: COMPILER=g++-5 CCOMPILER=gcc-5 GCOV="" COMPUTE_COVERAGE=false MAKE_DOC=false
      compiler: gcc

    # GCC 6
    - os: linux
      env: COMPILER=g++-6 CCOMPILER=gcc-6 GCOV=gcov-6 COMPUTE_COVERAGE=true MAKE_DOC=true
      compiler: gcc
      
    # OSX
    # Xcode 7.3
    - os: osx
      env: COMPUTE_COVERAGE=false
      osx_image: xcode7.3
      
    # Xcode 8
    - os: osx
      env: COMPUTE_COVERAGE=false
      osx_image: xcode8
     
install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  ############################################################################
  # Override compiler if needed
  ############################################################################
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; export CC=${CCOMPILER}; fi

  ############################################################################
  # For linux get docker image
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt install docker.io
      docker pull lubkoll/spacy-ci:base
    fi

  ############################################################################
  # For osx do the setup in travis
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      ############################################################################
      # Install a recent CMake
      ############################################################################
      mkdir ${DEPS_DIR}/cmake
      cd ${DEPS_DIR}/cmake
      curl http://github.com/Kitware/CMake/releases/download/v3.13.1/cmake-3.13.1.tar.gz -o cmake-3.13.1.tar.gz
      gunzip -c cmake-3.13.1.tar.gz | tar xopf -
      ./bootstrap --prefix=${DEPS_DIR} && make && make install
      export PATH="${DEPS_DIR}/bin:${PATH}"

      ############################################################################
      # Install gtest
      ############################################################################
      cd ${DEPS_DIR}
      git clone https://github.com/google/googletest.git && cd googletest
      mkdir -p build && cd build
      cmake -DCMAKE_CXX_FLAGS="${CXXFLAGS} -std=c++11" ..
      cmake --build .
      sudo make install
    fi

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      SHARED=/home/shared
      docker run --rm -ti -v ${TRAVIS_BUILD_DIR}:${SHARED} lubkoll/spacy-ci:base ${SHARED}/run_in_docker.sh ${CCOMPILER} ${COMPILER} ${GCOV} ${COVERALLS_TOKEN} ${COMPUTE_COVERAGE} ${MAKE_DOC}
    else
      mkdir build && cd build
      cmake -DBuildTest=ON -DCMAKE_CXX_FLAGS="-std=c++" ..
      cmake --build .
      cd Test && ctest
    fi

